export enum USER_STATUS {
  ACTIVE = "ACTIVE",
  BANNED = "BANNED",
  UNVERIFIED = "UNVERIFIED",
  DELETED = "DELETED",
}

export enum PROMOTION_LEVEL {
  ORDER = "ORDER",
  ITEM = "ITEM",
}

export enum PROMOTION_TYPE {
  PERCENT = "PERCENT",
  VALUE = "VALUE",
}
