export enum USER_STATUS {
  ACTIVE = "ACTIVE",
  BANNED = "BANNED",
  UNVERIFIED = "UNVERIFIED",
  DELETED = "DELETED",
}

export enum USER_GENDER {
  MALE = "MALE",
  FEMALE = "FEMALE",
  UNDEFINED = "UNDEFINED",
}

export enum PROMOTION_LEVEL {
  ORDER = "ORDER",
  ITEM = "ITEM",
}

export enum PROMOTION_TYPE {
  PERCENT = "PERCENT",
  VALUE = "VALUE",
}

export enum ABOUT_TYPE {
  Q_AND_A = "Q_AND_A",
  MAIN = "MAIN",
  CHILD = "CHILD",
}

export enum PAYMENT_METHOD {
  COD = "COD",
  CREDIT_CARD = "CREDIT_CARD",
}

export enum STATUS_ORDER {
  PENDING = "PENDING",
  ON_SHIPPING = "ON_SHIPPING",
  CANCEL = "CANCEL",
  DONE = "DONE",
  RETURN = "RETURN",
}

export enum CATEGORY_TYPE {
  CHILDREN = "CHILDREN",
  PARENT = "PARENT",
}

export enum REVIEW_SORT {
  OLDEST = "OLDEST",
  LATEST = "LATEST",
}
