import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainFooter from "@/components/layout/footer";
import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shopp",
  description: "Generated by create next app",
  icons: "/icon.jpg",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {children}
        <MainFooter />
        <Toaster />
      </body>
    </html>
  );
}
