export const ProductInCartsMockData = [
  {
    userId: 'user1',
    productId: 'p1',
    name: 'iPhone 13 Pro',
    avatar: 'iphone.jpg',
    quantity: 1,
    price: 999,
  },
  {
    userId: 'user1',
    productId: 'p2',
    name: 'Samsung 4K QLED TV',
    avatar: 'tv.jpg',
    quantity: 1,
    price: 1499,
  },
  {
    userId: 'user1',
    productId: 'p3',
    name: 'Dyson V11 Cordless Vacuum',
    avatar: 'vacuum.jpg',
    quantity: 1,
    price: 599,
  },
  {
    userId: 'user1',
    productId: 'p4',
    name: 'Apple MacBook Air M1',
    avatar: 'macbook.jpg',
    quantity: 1,
    price: 999,
  },
  {
    userId: 'user1',
    productId: 'p5',
    name: 'Bose Noise Cancelling Headphones 700',
    avatar: 'headphones.jpg',
    quantity: 1,
    price: 379,
  },
  {
    userId: 'user1',
    productId: 'p6',
    name: 'Nintendo Switch OLED Model',
    avatar: 'nintendo.jpg',
    quantity: 1,
    price: 349,
  },
  {
    userId: 'user2',
    productId: 'p7',
    name: 'Sony A7 III Mirrorless Camera',
    avatar: 'camera.jpg',
    quantity: 1,
    price: 1999,
  },
  {
    userId: 'user2',
    productId: 'p8',
    name: 'Cuisinart Stainless Steel Cookware Set',
    avatar: 'cookware.jpg',
    quantity: 1,
    price: 249,
  },
  {
    userId: 'user2',
    productId: 'p9',
    name: 'Fender Stratocaster Electric Guitar',
    avatar: 'guitar.jpg',
    quantity: 1,
    price: 1499,
  },
  {
    userId: 'user1',
    productId: 'p10',
    name: 'Dyson Supersonic Hair Dryer',
    avatar: 'hairdryer.jpg',
    quantity: 1,
    price: 399,
  },
  {
    userId: 'user2',
    productId: 'p11',
    name: 'Amazon Echo Show 10 (3rd Gen)',
    avatar: 'echo.jpg',
    quantity: 1,
    price: 249,
  },
  {
    userId: 'user1',
    productId: 'p12',
    name: 'Le Creuset Dutch Oven',
    avatar: 'dutchoven.jpg',
    quantity: 1,
    price: 349,
  },
  {
    userId: 'user3',
    productId: 'p13',
    name: 'Fitbit Versa 3 Smartwatch',
    avatar: 'smartwatch.jpg',
    quantity: 1,
    price: 229,
  },
  {
    userId: 'user3',
    productId: 'p14',
    name: 'Sony WH-1000XM4 Wireless Headphones',
    avatar: 'wirelessheadphones.jpg',
    quantity: 1,
    price: 349,
  },
  {
    userId: 'user1',
    productId: 'p15',
    name: 'Anker Portable Charger PowerCore',
    avatar: 'powerbank.jpg',
    quantity: 1,
    price: 49,
  },
  {
    userId: 'user3',
    productId: 'p16',
    name: 'Instant Pot Duo Evo Plus',
    avatar: 'instantpot.jpg',
    quantity: 1,
    price: 119,
  },
  {
    userId: 'user3',
    productId: 'p17',
    name: 'Philips Hue White and Color Ambiance Starter Kit',
    avatar: 'philipshue.jpg',
    quantity: 1,
    price: 189,
  },
  {
    userId: 'user1',
    productId: 'p18',
    name: 'Weber Spirit II E-310 Gas Grill',
    avatar: 'grill.jpg',
    quantity: 1,
    price: 479,
  },
  {
    userId: 'user3',
    productId: 'p19',
    name: 'Nespresso Vertuo Coffee and Espresso Machine',
    avatar: 'nespresso.jpg',
    quantity: 1,
    price: 199,
  },
  {
    userId: 'user3',
    productId: 'p20',
    name: 'Apple AirPods Pro',
    avatar: 'airpods.jpg',
    quantity: 1,
    price: 249,
  },
  {
    userId: 'user1',
    productId: 'p21',
    name: 'Yeti Tundra 45 Cooler',
    avatar: 'cooler.jpg',
    quantity: 1,
    price: 299,
  },
  {
    userId: 'user1',
    productId: 'p22',
    name: 'Samsung Odyssey G7 Gaming Monitor',
    avatar: 'monitor.jpg',
    quantity: 1,
    price: 699,
  },
  {
    userId: 'user1',
    productId: 'p23',
    name: 'iRobot Roomba i7+ Robot Vacuum',
    avatar: 'roomba.jpg',
    quantity: 1,
    price: 799,
  },
  {
    userId: 'user1',
    productId: 'p24',
    name: 'All-Clad Stainless Steel Fry Pan',
    avatar: 'frypan.jpg',
    quantity: 1,
    price: 99,
  },
  {
    userId: 'user1',
    productId: 'p25',
    name: 'Breville Barista Express Espresso Machine',
    avatar: 'espressomachine.jpg',
    quantity: 1,
    price: 599,
  },
  {
    userId: 'user1',
    productId: 'p26',
    name: 'SodaStream Fizzi Sparkling Water Maker',
    avatar: 'sodastream.jpg',
    quantity: 1,
    price: 89,
  },
  {
    userId: 'user1',
    productId: 'p27',
    name: 'Samsung Galaxy Watch 4',
    avatar: 'galaxywatch.jpg',
    quantity: 1,
    price: 249,
  },
  {
    userId: 'user1',
    productId: 'p28',
    name: 'TCL 55-Inch 4K Smart TV',
    avatar: 'tcltv.jpg',
    quantity: 1,
    price: 499,
  },
  {
    userId: 'user1',
    productId: 'p29',
    name: 'KitchenAid Artisan Stand Mixer',
    avatar: 'standmixer.jpg',
    quantity: 1,
    price: 399,
  },
  {
    userId: 'user1',
    productId: 'p30',
    name: 'GoPro HERO10 Black',
    avatar: 'gopro.jpg',
    quantity: 1,
    price: 499,
  },
];
