export const UserMockData = [
  {
    id: 'user1',
    name: 'John Doe',
    birthDate: '1985-03-15',
    status: 1,
    address: '123 Main St, Anytown, USA',
  },
  {
    id: 'user2',
    name: 'Alice Johnson',
    birthDate: '1990-09-22',
    status: 1,
    address: '456 Oak Ave, Springfield, USA',
  },
  {
    id: 'user3',
    name: 'Michael Smith',
    birthDate: '1988-06-10',
    status: 1,
    address: '789 Elm Rd, Lakeside, USA',
  },
  {
    id: 'user4',
    name: 'Emily Brown',
    birthDate: '1995-12-03',
    status: 1,
    address: '321 Pine Blvd, Mountain View, USA',
  },
  {
    id: 'user5',
    name: 'David Wilson',
    birthDate: '1983-04-28',
    status: 1,
    address: '567 Cedar Ln, Rivertown, USA',
  },
  {
    id: 'user6',
    name: 'Sophia Lee',
    birthDate: '1992-07-17',
    status: 1,
    address: '890 Maple Ave, Harbor City, USA',
  },
  {
    id: 'user7',
    name: 'Daniel Taylor',
    birthDate: '1987-01-09',
    status: 1,
    address: '432 Birch St, Sunnyside, USA',
  },
  {
    id: 'user8',
    name: 'Olivia Garcia',
    birthDate: '1993-11-12',
    status: 1,
    address: '654 Pinecrest Dr, Hilltop, USA',
  },
  {
    id: 'user9',
    name: 'James Robinson',
    birthDate: '1984-08-20',
    status: 1,
    address: '876 Willow Ave, Lakeshore, USA',
  },
  {
    id: 'user10',
    name: 'Emma Martinez',
    birthDate: '1991-05-07',
    status: 1,
    address: '987 Forest Rd, Riverdale, USA',
  },
];
