-- AlterTable
ALTER TABLE "Image" ALTER COLUMN "width" DROP NOT NULL,
ALTER COLUMN "height" DROP NOT NULL,
ALTER COLUMN "cloudName" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "avatar" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "birthDate" DROP NOT NULL,
ALTER COLUMN "avatar" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL;
