version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=aA@12345678
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - shopp

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=shopp@123456789
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    networks:
      - shopp

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - shopp

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - shopp

networks:
  shopp:
    driver: bridge
