name: CI/CD Pipeline for NestJS

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x"

      - name: Install dependencies
        run: |
          cd BE
          npm cache clean --force
          npm install -g @nestjs/cli
          npm install --force
          npm run prisma:generate

      - name: Run lint
        run: |
          cd BE
          npm run lint

      - name: Run GitLeaks
        run: |
          cd BE
          npm run gitleaks

      - name: Run tests
        run: |
          cd BE
          npm run test:ci

      - name: Publish test results to docs
        if: always()
        run: |
          mkdir -p docs/test-results
          cp BE/**/test-report.xml docs/test-results/

      - name: Publish code coverage results to docs
        if: always()
        run: |
          mkdir -p docs/coverage
          cp BE/coverage/cobertura-coverage.xml docs/coverage/

      - name: Run npm audit
        run: |
          cd BE
          npm audit --audit-level=high
        continue-on-error: true

      - name: Build project
        run: |
          cd BE
          npm run build

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
